yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment',
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'

handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Post(CreatedModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Добавьте картинку',
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField('slug', unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow',
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'text'}

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

POSTS_LIST: int = 10  # Количество постов выводимых на странице


def paginator(request, queryset):
    paginator = Paginator(queryset, POSTS_LIST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return {'page_obj': page_obj}


# Главная страница
def index(request):
    post_list = Post.objects.all()

    context = paginator(request, post_list)

    return render(request, 'posts/index.html', context)


# Страница с группами публикаций
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()

    context = {'group': group}
    context.update(paginator(request, post_list))

    return render(request, 'posts/group_list.html', context)


# Профайл пользователя
def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list_user = author.posts.all()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user.id,
        author=author,
    ).exists()

    context = {
        'author': author,
        'post_list_user': post_list_user,
        'following': following,
    }
    context.update(paginator(request, post_list_user))
    return render(request, 'posts/profile.html', context)


# Детальный просмотр отдельного поста
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


# Создание поста
@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        return redirect("posts:profile", request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


# Редактирование поста
@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post.id)

    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None,
    )
    context = {'form': form, 'is_edit': True}

    if form.is_valid():
        form.save()

        return redirect('posts:post_detail', post_id=post.id)
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    follow_post_list = Post.objects.filter(
        author__following__user=request.user
    )

    context = paginator(request, follow_post_list)

    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author and not Follow.objects.filter(
        user=user,
        author=author,
    ).exists():
        Follow.objects.create(
            user=user,
            author=author,
        )

    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=user,
        author=author,
    )
    follow.delete()

    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}

{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать пост
                {% else %}
                  Новый пост
                {% endif %}
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                      <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text"
                      >{% if is_edit %}{{ form.text }}{% endif %}</textarea>
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      {% for group in form.group %}
                        {{ group }}
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
                  </div>

                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{#  {% load cache %}#}

{% block title %}
  Последние обновления на сайте
{% endblock %}


{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {#  {% cache 20 index_page %}#}
  {% for post in page_obj %}

    <ul>
      <li>
        Автор:
        <a href="{% url 'posts:profile' post.author.username  %}">
          {{ post.author.get_full_name }}
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group.slug %}
      <li>
        Группа:
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a>
      </li>
      {% endif %}
    </ul>
     {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
       <img class="card-img my-2" src="{{ im.url }}">
     {% endthumbnail %}
    <p>{{ post.text }}</p>
    <p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    </p>

    {% if not forloop.last %}<hr>{% endif %}

  {% endfor %}
{#{% endcache %}#}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}
  {{ group }}
{% endblock %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: <a href="{% url 'posts:profile' post.author.username  %}">
          {{ post.author.get_full_name }}
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
      </p>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load cache %}


{% block title %}
  Последние обновления на сайте
{% endblock %}


{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% cache 20 index_page %}
  {% for post in page_obj %}

    <ul>
      <li>
        Автор:
        <a href="{% url 'posts:profile' post.author.username  %}">
          {{ post.author.get_full_name }}
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group.slug %}
      <li>
        Группа:
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a>
      </li>
      {% endif %}
    </ul>
     {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
       <img class="card-img my-2" src="{{ im.url }}">
     {% endthumbnail %}
    <p>{{ post.text }}</p>
    <p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    </p>

    {% if not forloop.last %}<hr>{% endif %}

  {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}
    Пост {{ post|truncatechars:30 }}
{% endblock %}

{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор: <a href="{% url 'posts:profile' post.author.username  %}">
              {{ post.author.get_full_name }}
              </a>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>

            {% if user == post.author %}
            <li class="list-group-item">
              <a href="{% url 'posts:post_edit' post.id %}">
                Редактировать
              </a>
            </li>
            {% endif %}

          </ul>
        </aside>

        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post }}
          </p>
        </article>

       {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %}

      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}
    Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}

  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }} </h1>
      <h3>Всего постов: {{ post_list_user.count }}</h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
     {% endif %}
    </div>

    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ author.get_full_name }}
            <a href="{% url 'posts:profile' author.username %}">все посты пользователя</a>
          </li>
        </ul>
          <ul>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>

          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}

          <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.id  %}">подробная информация </a>
      </article>

      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug  %}">все записи группы {{ post.group }}</a>
      {% endif %}


      {% if not forloop.last %}<hr>{% endif %}
     {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>

{% endblock %}